# Generated by Django 2.1.7 on 2019-03-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creation_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='creation_date',
            new_name='publication_date',
        ),
    ]
